export const SET_PHOTOS = 'SET_PHOTOS';
export const SET_PHOTOS_FAILED = 'SET_PHOTOS_FAILED';
export const INITIATE_GET_PHOTOS = 'INITIATE_GET_PHOTOS';

export const INITIATE_GET_PROFILE = 'INITIATE_GET_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILE_FAILED = 'SET_PROFILE_FAILED';

export const INITIATE_GET_SINGLE_PHOTO = 'INITIATE_GET_SINGLE_PHOTO';
export const SET_SINGLE_PHOTO = 'SET_SINGLE_PHOTO';
export const SET_SINGLE_PHOTO_FAILED = 'SET_SINGLE_PHOTO_FAILED';

export const INITIATE_POST_COMMENT = 'INITIATE_POST_COMMENT';
export const POST_COMMENT_FAILED = 'POST_COMMENT_FAILED';
export const INITIATE_GET_COMMENTS = 'INITIATE_GET_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS'
export const SET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED';
export const SET_SINGLE_COMMENT = 'SET_SINGLE_COMMENT';
