export const SET_PHOTOS = 'SET_PHOTOS';
export const SET_PHOTOS_FAILED = 'SET_PHOTOS_FAILED';
export const INITIATE_GET_PHOTOS = 'INITIATE_GET_PHOTOS';

export const INITIATE_GET_PROFILE = 'INITIATE_GET_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILE_FAILED = 'SET_PROFILE_FAILED';